### ISSUE TITLE
PMPI Replacement Interface

### ISSUE THREAD

**Issue by kathrynmohror** [mpiwg-tools/tools-issues#1]
The discussion of this topic is maintained on this page: https://github.com/mpiwg-tools/tools-issues/wiki/Interface-to-Replace-PMPI. There you can find high-level information and a pointer to the most recent state of the interface.

**Comment by mahermanns** [comment]
Closing this internal ticket in favor of the MPI Forum ticket at https://github.com/mpi-forum/mpi-issues/issues/638

Any further discussion will be held on that ticket.
