### ISSUE TITLE
MPI_T: MPI application vs MPI process

### ISSUE THREAD

**Issue by kathrynmohror** [mpiwg-tools/tools-issues#10]
From the March 2016 Forum meeting discussions, we noted that we may not be consistent with the rest of the Standard in our usage of "MPI application" and "MPI process" in the tools chapter.

We need to go through and evaluate this.

**Comment by mahermanns** [comment]
This also touches/involves the use of the word "run", right? Should this rather be "execution"?

**Comment by mahermanns** [comment]
As discussed in the call on May 11, 2017, I annotated each occurrence of 'process' in the tools chapter and marked those that we agreed on that would need changes. Check the [PDF](https://github.com/mpiwg-tools/tools-issues/files/995953/mpi31-report_t-issue-10-annotated.pdf) to see if I transcribed our decisions correctly.

**Comment by esthela** [comment]
I was looking at the PDF, and noticed that the use of 'MPI' before each occurrence of 'process' or 'application' is not consistent throughout the chapter. Is that something that should be addressed as well?  An example is in lines 15-17 vs. 38-40.

**Comment by kathrynmohror** [comment]
Esthela, I am not sure what page you mean so I am not looking at the particular example you are pointing out. However, digging through the rest of the standard, the use of 'MPI' before process or application is also not consistent. The rule seems to be as long as the reader can tell what is meant from the context then it is okay to use or not use the descriptive 'MPI' before process or application.

**Comment by mahermanns** [comment]
Related changes to the chapter are available in the branch [mpiwg-tools/mpi-standard:issue_10_refinded_process_references](https://github.com/mpiwg-tools/mpi-standard/tree/issue_10_refined_process_references).
