### ISSUE TITLE
Code Example Bug: Example 14.4 in MPI 3.1

### ISSUE THREAD

**Issue by kathrynmohror** [mpiwg-tools/tools-issues#4]
The CVAR example in the official 3.1 document Section 14.3 (MPI Tool CVAR) page 577 compiles but doesn¹t do the expected work. One must change the || at line 7 into && to have it perform as advertised.

Replace page 577 line 7:
`if (err!=MPI_SUCCESS || err!=MPI_T_ERR_INVALID_INDEX) return err;`

with 
`if (err!=MPI_SUCCESS && err!=MPI_T_ERR_INVALID_INDEX) return err;`

Should this be an errata item, or ticket 0?

**Comment by jsquyres** [comment]
My $0.02: errata.

**Comment by kathrynmohror** [comment]
Discussed this in working group meeting on 11/5/15 and decided that handling it as errata is best.

**Comment by kathrynmohror** [comment]
Now moved to [Forum Issue #12](https://github.com/mpi-forum/mpi-issues/issues/12)
