### ISSUE TITLE
MPI_T: Deprecate MPI_T_ERR_INVALID_ITEM

### ISSUE THREAD

**Issue by kathrynmohror** [mpiwg-tools/tools-issues#6]
Old ticket [#410](https://svn.mpi-forum.org/trac/mpi-forum-web/ticket/410)

We inadvertently added two error codes for MPI_T that essentially have the same meaning. We want to deprecate MPI_T_ERR_INVALID_ITEM:

page 589 line 13 remove:

MPI_T_ERR_INVALID_ITEM The item index queried is out of range (for MPI_T_ENUM_GET_ITEM only)

**Comment by mahermanns** [comment]
This is superseded by mpi-forum/mpi-issues#60.
